// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BaseAside: typeof import("./components/layout/BaseAside.vue")["default"];
    BaseFooter: typeof import("./components/layout/BaseFooter.vue")["default"];
    BaseHeader: typeof import("./components/layout/BaseHeader.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
